### 3.2.1 From Python lists to PyTorch tensors

In [1]:
a = [1.0, 2.0, 1.0]

In [2]:
a[0]

1.0

In [3]:
a[2] = 3.0
a

[1.0, 2.0, 3.0]

### 3.2.2 Constructing our first tensors

In [4]:
import torch

In [5]:
a = torch.ones(3)
a

tensor([1., 1., 1.])

In [6]:
a[1]

tensor(1.)

In [7]:
float(a[1])

1.0

In [8]:
a[2] = 2.0
a

tensor([1., 1., 2.])

### 3.2.3 The essence of tensors

- 1-D tensor storing Xs in the even indices and Ys in the odd indices:

In [9]:
# using .zeros is just a way to get an appropriately sized array.
points = torch.zeros(6)
points[0] = 4.0
points[1] = 1.0
points[2] = 5.0
points[3] = 3.0
points[4] = 2.0
points[5] = 1.0

- can also pass a Python list to the constructor:

In [10]:
points = torch.tensor([4.0, 1.0, 5.0, 3.0, 2.0, 1.0])
points

tensor([4., 1., 5., 3., 2., 1.])

In [11]:
float(points[0]), float(points[1])

(4.0, 1.0)

- It would be practical to have the first index refer to individual 2D points rather than point coordinates.
- なのでuse a 2D tensor:

In [12]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [13]:
points.shape

torch.Size([3, 2])

In [14]:
points = torch.zeros(3, 2)
points

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [15]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

- access an individual element in the tensor using two indices:

In [16]:
points[0, 1]

tensor(1.)

In [17]:
points[0]

tensor([4., 1.])

- The output is another tensor that presents **a different view of the same underlying data**.

## 3.3 Indexing tensors

- Python listのindexing:

In [18]:
some_list = list(range(6))
some_list

[0, 1, 2, 3, 4, 5]

In [19]:
some_list[:]

[0, 1, 2, 3, 4, 5]

In [20]:
# from element 1 inclusive to element 4 exclusive
some_list[1:4]

[1, 2, 3]

In [21]:
some_list[1:]

[1, 2, 3, 4, 5]

In [22]:
some_list[:4]

[0, 1, 2, 3]

In [23]:
# from the start of the list to one before the last element
some_list[:-1]

[0, 1, 2, 3, 4]

In [24]:
# from element 1 inclusive to element 4 exclusive, in steps of 2
some_list[1:4:2]

[1, 3]

- use the same notation for PyTorch tensors:

In [25]:
# all rows after the first; implicitly all columns
points[1:]

tensor([[5., 3.],
        [2., 1.]])

In [26]:
# all rows after the first; all columns
points[1:, :]

tensor([[5., 3.],
        [2., 1.]])

In [27]:
# all rows after the first; first column
points[1:, 0]

tensor([5., 2.])

In [28]:
# add a dimension of size 1, just like unsqueeze
points[None]

tensor([[[4., 1.],
         [5., 3.],
         [2., 1.]]])

In [30]:
points[None].shape

torch.Size([1, 3, 2])

- `points[None]`はpointsを変更しないよ、viewだけだから。
- In addition to using ranges, PyTorch features a powerful form of indexing, called *advanced indexing*. 次の章。