- Create a tensor `a` from `list(range(9))` . Predict and then check the size, offset, and stride.
    - Create a new tensor using `b = a.view(3, 3)` . What does `view` do? Check that `a` and `b` share the same storage.
    - Create a tensor `c = b[1:,1:]` . Predict and then check the size, offset, and stride.

In [1]:
import torch

In [2]:
a = torch.tensor(list(range(9)))

In [3]:
a

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [4]:
a.size(), a.storage_offset(), a.stride()

(torch.Size([9]), 0, (1,))

In [5]:
b = a.view(3, 3)

In [6]:
id(a.storage()) == id(b.storage())

True

In [7]:
b

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [8]:
c = b[1:, 1:]

In [9]:
# 予想：(2, 2), 4, (3, 1) 
c.size(), c.storage_offset(), c.stride()

(torch.Size([2, 2]), 4, (3, 1))

- Pick a mathematical operation like cosine or square root. Can you find a corresponding function in the `torch` library?
    - Apply the function element-wise to `a` . Why does it return an error?
    - What operation is required to make the function work?
    - Is there a version of your function that operates in place?

In [10]:
a.cos()

RuntimeError: cos_vml_cpu not implemented for 'Long'

In [11]:
a.float().cos()

tensor([ 1.0000,  0.5403, -0.4161, -0.9900, -0.6536,  0.2837,  0.9602,  0.7539,
        -0.1455])

In [12]:
a

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [13]:
a = a.float()
a

tensor([0., 1., 2., 3., 4., 5., 6., 7., 8.])

In [14]:
a.cos_()

tensor([ 1.0000,  0.5403, -0.4161, -0.9900, -0.6536,  0.2837,  0.9602,  0.7539,
        -0.1455])

In [15]:
a

tensor([ 1.0000,  0.5403, -0.4161, -0.9900, -0.6536,  0.2837,  0.9602,  0.7539,
        -0.1455])